export const UPDATE_CITY_LIST = 'UPDATE_CITY_LIST';
export const SET_API_DATA = 'SET_API_DATA';
export const REMOVE_CITY = 'REMOVE_CITY';
export const ADD_INITIAL_CITY_LIST = 'ADD_INITIAL_CITY_LIST';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const LOADING = 'LOADING';
